Global:
  use_gpu: True
  epoch_num: 1000
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: /project/train/models/rec/mv3_none_bilstm_ctc/
  save_epoch_step: 2000
  # evaluation is run every 2000 iterations
  eval_batch_step: [0, 2000]
  cal_metric_during_train: True
  pretrained_model: /project/train/models/rec/mv3_none_bilstm_ctc/best_accuracy
  checkpoints:
  save_inference_dir:
  use_visualdl: False
  infer_img: /project/train/src_repo/PaddleOCR/plate_test.jpg
  # for data or label process
  character_dict_path: /project/train/src_repo/PaddleOCR/ppocr/utils/dict/plate_dict.txt
  max_text_length: 8
  infer_mode: False
  use_space_char: False
  save_res_path: ./output/rec/predicts_mv3_none_bilstm_ctc.txt

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    learning_rate: 0.0005
  regularizer:
    name: 'L2'
    factor: 0

Architecture:
  model_type: rec
  algorithm: CRNN
  Transform:
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: large
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 96
  Head:
    name: CTCHead
    fc_decay: 0

Loss:
  name: CTCLoss

PostProcess:
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /home/data/ocr_data/ocr_crop_imgs/
    label_file_list:
      - /home/data/ocr_data/ocr_train.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: True
    batch_size_per_card: 64
    drop_last: True
    num_workers: 4

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /home/data/ocr_data/ocr_crop_imgs/
    label_file_list:
      - /home/data/ocr_data/ocr_test.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - CTCLabelEncode: # Class handling label
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label', 'length'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 64
    num_workers: 4
